[versions]
fx = "17-ea+6"
kotlin = "1.5.0"
ktlang = "1.5"
java = "13"
multik="0.0.1"
[libraries]

kt-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kt-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

fx-base = { group = "org.openjfx", name = "javafx-base", version.ref = "fx" }
fx-controls = { group = "org.openjfx", name = "javafx-controls", version.ref = "fx" }
fx-graphics = { group = "org.openjfx", name = "javafx-graphics", version.ref = "fx" }
fx-web = { group = "org.openjfx", name = "javafx-web", version.ref = "fx" }
fx-media = { group = "org.openjfx", name = "javafx-media", version.ref = "fx" }

gson = { module = "com.google.code.gson:gson", version = "2.8.6" }
toml = { module = "org.tomlj:tomlj", version = "1.0.0" }

multik-default = { module = "org.jetbrains.kotlinx:multik-default", version.ref = "multik" }
multik-api = { module = "org.jetbrains.kotlinx:multik-api", version.ref = "multik" }

[bundles]
fx-full = ["fx-base", "fx-controls", "fx-graphics", "fx-web", "fx-media"]
multik-full = ["multik-default", 'multik-api']